# Generated by Django 4.2.6 on 2024-05-31 08:38

from django.db import migrations, models
import profiles.utils.upload_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('email_is_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Phone Number')),
                ('phone_number_is_verified', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=32, verbose_name='City')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('avatar', models.ImageField(blank=True, upload_to=profiles.utils.upload_path.profile_upload, verbose_name='Avatar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
