version: "3.8"
services:
  celery_service:
    restart: always
    container_name: celery_service
    build:
      context: ../..
      dockerfile: ./doker/celery/celery.Dockerfile
    command: /celery.Runner
    volumes:
      - .:/app
    networks:
      - celery_service_network

networks:
  celery_service_network:
    driver: bridge

