# Generated by Django 4.2.6 on 2024-01-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminstration', '0003_emailtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.DeleteModel(
            name='SMSTemplate',
        ),
    ]
