# Generated by Django 4.2.6 on 2024-01-04 12:47
# Edited by hand to rename field

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "profiles",
            "0003_profileaddress_is_primary_profileemail_is_verified_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilephonenumber",
            old_name="number",
            new_name="phone_number",
        )
    ]
