# Generated by Django 4.2.6 on 2024-01-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profilephonenumber_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephonenumber',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='Phone Number'),
        ),
    ]
