# Generated by Django 4.2.6 on 2024-01-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_profile_email_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profileemail',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('email',), name='unique_if_not_deleted_profile_email'),
        ),
        migrations.AddConstraint(
            model_name='profilephonenumber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('phone_number',), name='unique_if_not_deleted_profile_phone_number'),
        ),
    ]
