version: "3.8"
services:
  redis_service:
    image: redis:alpine
    container_name: redis_server
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - redis_server_network

networks:
  redis_server_network:
    driver: bridge
